version: '3.8'
services:
  lizmap:
    container_name: lizmap-${SUFFIX_NAME}
    image: 3liz/lizmap-web-client:${LIZMAP_VERSION_TAG}
    # user: ${LIZMAP_UID}:${LIZMAP_UID}
    environment:
      LIZMAP_CACHEREDISDB: '{REDISID}'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      LIZMAP_USER: ${LIZMAP_UID}
      LIZMAP_WMSSERVERURL: http://map-${SUFFIX_NAME}:8080/ows/
      LIZMAP_CONFIG_INCLUDE: /srv/etc
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGPASSFILE: /srv/etc/pgpass.conf
    volumes:
      - ${NEXTCLOUD_PATH}/${SUFFIX_NAME}/files/:/srv/projects:rw
      - ${LIZMAP_DIR}/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${LIZMAP_DIR}/var/lizmap-config:/www/lizmap/var/config
      - ${LIZMAP_DIR}/var/lizmap-db:/www/lizmap/var/db
      - ${LIZMAP_DIR}/www:/www/lizmap/www
      - ${LIZMAP_DIR}/www/var/log:/www/lizmap/var/log
      - ${LIZMAP_DIR}/var/lizmap-modules:/www/lizmap/lizmap-modules
      - ${LIZMAP_DIR}/var/lizmap-my-packages:/www/lizmap/my-packages
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
    command:
      - php-fpm
    restart: unless-stopped
  qgis-server:
    container_name: qgisserver-${SUFFIX_NAME}
    build: 
      context: ../../qgis/docker/qgis-server
      dockerfile: Dockerfile
    user: ${LIZMAP_UID}:${LIZMAP_GID}
    volumes:
      - ${NEXTCLOUD_PATH}/${SUFFIX_NAME}/files/:/srv/projects:rw
      - ${LIZMAP_DIR}/plugins:/srv/plugins
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      PGSPASSFILE: /srv/etc/pgpass.conf
      LANG: en_EN.UTF-8
      QGIS_SERVER_LOG_LEVEL: 0
      QGIS_SERVER_LIZMAP_REVEAL_SETTINGS: 1
      QGIS_PLUGINPATH: /srv/plugins
      QGIS_SERVER_CACHE_SIZE: 200
      QGIS_SERVER_CAPABILITIES_CACHE_SIZE: 100
      #QGIS_SERVER_PARALLEL_RENDERING: 1
      DEBUG: 1
    restart: unless-stopped
  map:
    container_name: map-${SUFFIX_NAME}
    image: nginx:alpine
    ports:
      - ${OWS_PORT}:80
    volumes:
      - ../../qgis/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-server
  nginx:
    image: nginx:alpine
    container_name: nginx-web-${SUFFIX_NAME}
    # user: ${LIZMAP_UID}:${LIZMAP_GID}
    volumes:
      - ${LIZMAP_DIR}/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${LIZMAP_DIR}/var/log/nginx:/var/log/nginx
      - ${LIZMAP_DIR}/var/nginx-cache:/var/cache/nginx
      - ${LIZMAP_DIR}:/srv/lizmap
    ports:
      - ${LIZMAP_PORT}:${LIZMAP_ONLY_PORT}
    depends_on:
      - lizmap
    environment:
      VIRTUAL_HOST: ${LIZMAP_ADDRESS}
      VIRTUAL_PORT: ${LIZMAP_ONLY_PORT}
      LETSENCRYPT_HOST: ${LIZMAP_ADDRESS}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}

networks:
  default:
    external: true
    name: nginx-proxy-net
