#!/bin/bash
set -e

echo "CREATE ROLE, DATABASE and SCHEMA for Lizmap"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE "$POSTGRES_LIZMAP_USER" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD '$POSTGRES_LIZMAP_PASSWORD';
	CREATE DATABASE "$POSTGRES_LIZMAP_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_LIZMAP_DB" TO "$POSTGRES_LIZMAP_USER";
EOSQL

echo "CREATE EXTENSION postgis"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_LIZMAP_DB" <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS "postgis";
        CREATE EXTENSION IF NOT EXISTS "postgis_raster";
        CREATE SCHEMA "lizmap" AUTHORIZATION "$POSTGRES_LIZMAP_USER";
EOSQL

echo "CREATE DATABASE nextcloud"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE nextcloud;
	GRANT ALL PRIVILEGES ON DATABASE nextcloud TO "$POSTGRES_LIZMAP_USER";
EOSQL

echo "CREATE DATABASE gishosting2"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE gishosting2;
        GRANT ALL PRIVILEGES ON DATABASE gishosting2 TO "$POSTGRES_LIZMAP_USER";
EOSQL
