#!/bin/bash
set -e

echo "DENTRO ALLO SCRIPT"

echo "CREATE DATABASE $POSTGRES_LIZMAP_DB"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE "$POSTGRES_LIZMAP_USER" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD '$POSTGRES_LIZMAP_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_LIZMAP_DB" TO "$POSTGRES_LIZMAP_USER";
EOSQL
echo "SELECT 'CREATE DATABASE "$POSTGRES_LIZMAP_DB"' WHERE NOT EXISTS (SELECT * FROM pg_database WHERE datname = '"$POSTGRES_LIZMAP_DB"')\gexec"

echo 'CREATE EXTENSION "postgis";'
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_LIZMAP_DB" <<-EOSQL
	CREATE EXTENSION "postgis_raster";
        CREATE SCHEMA "lizmap" AUTHORIZATION "$POSTGRES_LIZMAP_USER";
EOSQL

echo "CREATE DATABASE nextcloud"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE nextcloud;
	GRANT ALL PRIVILEGES ON DATABASE nextcloud TO "$POSTGRES_LIZMAP_USER";
EOSQL

echo "CREATE DATABASE gishosting2"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE gishosting2;
        GRANT ALL PRIVILEGES ON DATABASE nextcloud TO "$POSTGRES_LIZMAP_USER";
EOSQL
